#!/usr/bin/env bash
#
# test_regression.sh — compare output of original vs new fitsverify
#
# Usage: run from the build/tests directory after building.
#   bash test_regression.sh
#
# Prerequisites:
#   - ../cli/fitsverify  (new build, in build/cli/)
#   - Original fitsverify built from source/c/ as fitsverify_orig
#   - Test FITS files generated by gen_test_fits
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$(cd "$SCRIPT_DIR/../../source/c" 2>/dev/null && pwd || true)"
NEW_FV="$SCRIPT_DIR/../cli/fitsverify"
ORIG_FV="$SCRIPT_DIR/fitsverify_orig"

# If we don't have test files, generate them
if [ ! -f "$SCRIPT_DIR/valid_minimal.fits" ]; then
    echo "Generating test FITS files..."
    "$SCRIPT_DIR/gen_test_fits"
fi

# Build original fitsverify if not already built
if [ ! -x "$ORIG_FV" ] && [ -d "$SRC_DIR" ]; then
    echo "Building original fitsverify..."
    cc -w -DSTANDALONE -DERR2OUT \
       "$SRC_DIR/ftverify.c" \
       "$SRC_DIR/fvrf_data.c" \
       "$SRC_DIR/fvrf_file.c" \
       "$SRC_DIR/fvrf_head.c" \
       "$SRC_DIR/fvrf_key.c" \
       "$SRC_DIR/fvrf_misc.c" \
       -I"$SRC_DIR" \
       $(pkg-config --cflags --libs cfitsio 2>/dev/null || echo "-lcfitsio") \
       -lm -o "$ORIG_FV"
    echo "  built $ORIG_FV"
fi

if [ ! -x "$ORIG_FV" ]; then
    echo "WARNING: Could not build original fitsverify (source/c/ not found)."
    echo "         Skipping regression comparison."
    exit 0
fi

if [ ! -x "$NEW_FV" ]; then
    echo "ERROR: New fitsverify not found at $NEW_FV"
    exit 1
fi

# Test files to compare
TEST_FILES=(
    valid_minimal.fits
    valid_multi_ext.fits
    err_dup_extname.fits
)

# Note: files that cause errors that terminate early or have different
# behavior (err_bad_bitpix, err_missing_end) may have minor differences
# and are tested separately.

PASS=0
FAIL=0

for f in "${TEST_FILES[@]}"; do
    fpath="$SCRIPT_DIR/$f"
    if [ ! -f "$fpath" ]; then
        echo "SKIP: $f (not found)"
        continue
    fi

    orig_out=$(mktemp)
    new_out=$(mktemp)

    # Run both, capturing stdout+stderr merged
    "$ORIG_FV" "$fpath" > "$orig_out" 2>&1 || true
    "$NEW_FV" "$fpath" > "$new_out" 2>&1 || true

    # Filter out banner lines (version, separator, blank lines at top)
    # and HEASARC/HIERARCH convention messages
    grep -v "fitsverify" "$orig_out" | grep -v "^[[:space:]]*-*[[:space:]]*$" | \
        grep -v "HEASARC conventions" | grep -v "ESO HIERARCH" | \
        sed '/^[[:space:]]*$/d' > "${orig_out}.filtered"
    grep -v "fitsverify" "$new_out" | grep -v "^[[:space:]]*-*[[:space:]]*$" | \
        grep -v "HEASARC conventions" | grep -v "ESO HIERARCH" | \
        sed '/^[[:space:]]*$/d' > "${new_out}.filtered"

    if diff -u "${orig_out}.filtered" "${new_out}.filtered" > /dev/null 2>&1; then
        echo "PASS: $f"
        PASS=$((PASS + 1))
    else
        echo "FAIL: $f"
        echo "--- diff (original vs new) ---"
        diff -u "${orig_out}.filtered" "${new_out}.filtered" || true
        echo "--- end diff ---"
        FAIL=$((FAIL + 1))
    fi

    rm -f "$orig_out" "$new_out" "${orig_out}.filtered" "${new_out}.filtered"
done

echo ""
echo "=== Regression Results: $PASS passed, $FAIL failed ==="
exit $FAIL
